### ISSUE TITLE
Request failed with status code 400 : extra keys not allowed @ data['is_shared_with_project']. Got False

### ISSUE THREAD

**Issue by adi2907** [ak--47/mpMigrate#12]
Getting the error Request failed with status code 400 : extra keys not allowed @ data['is_shared_with_project']. Got False when trying to migrate from one project to anther. The output I am getting is this

creating 1 dashboard(s) with...
	7 reports
	0 media object
	0 text cards
ERROR MAKING DASH! DA Dashboard
Request failed with status code 400 : extra keys not allowed @ data['is_shared_with_project']. Got False
	... 👍 created 1 dashboards
	... 👍 created 0 reports
	... 👍 created 0 media objects
	... 👍 created 0 text cards

No dashboard was created. 

Am selecting "No" for all the options being asked
do you want to copy all EVENTS from project 2799628 to project 2798949? No
do you want to copy all PROFILES from project 2799628 to project 2798949? No
do you want to copy the SCHEMA (lexicon) from project 2799628 to project 2798949? No
do you want to generate a log of everything that was done? Yes

Can't share steps to reproduce but if you can see there's an issue due to mixpanel new version, will really appreciate. Thanks

**Comment by ak--47** [comment]
@adi2907 thanks for the report... i will take a look...

**Comment by ak--47** [comment]
@adi2907 this is fixed
https://github.com/ak--47/mpMigrate/blob/main/endpoints.js#L185

plz make sure you run the latest version:

```
npx mp-migrate@latest
```

**Comment by adi2907** [comment]
@ak--47 Perfect. Thanks a lot. You are doing a great service to Mixpanel users
