### ISSUE TITLE
insert_id missing

### ISSUE THREAD

**Issue by eMerzh** [ak--47/mpMigrate#14]
Hello :) thanks for your project,, it looks really interesing...

i'm trying to migrate oldish events, but i got a lot of errors with those:
```
        {
          "index": 1088,
          "field": "properties.$insert_id",
          "message": "'properties.$insert_id' is invalid: must not be missing"
        },
```

any idea how to turn around it? 

thanks =)

**Comment by ak--47** [comment]
@eMerzh interesting... the 'under the hood' code is essentially doing `/export` then `/import`, and i'd be surprised if events came back from mixpanel _without_ an `$insert_id`

fwiw, this project was MOSTLY about migrating reports and dashboards... it kinda struggles with large or any kind of detailed troubleshooting.

specifically for migrating your data, i'd check out my _other_ package **[mixpanel-import](https://github.com/ak--47/mixpanel-import#readme)** ... it uses streams E2E and gives you many more transform options... makes it easy to export and inspect the data before your import... 

here's a gist on how you move stuff using that as a CLI:
https://gist.github.com/ak--47/05d73181bf85d4b47317dee9d16aed4d

let me know if that works better for you.

**Comment by eMerzh** [comment]
@ak--47 thanks for looking into this, 
yes, I dug a bit deeper in this, and events are coming straight from mixpanel like that.
I tried manually to import them but same issue,

I guess the fact that they are from 2018 might explain that 🤔 
do you know if i can just generate one and upload it again ? Like in a middle step (with mpMigrate or manually) ?

**Comment by ak--47** [comment]
use [mixpanel-import](https://github.com/ak--47/mixpanel-import#-options) ... it allows sending in non strict mode... check out the gist, i promise it's not crazy!

**Comment by ak--47** [comment]
@eMerzh circling back, are you unblocked here?

**Comment by eMerzh** [comment]
sorry for the delay and many thanks for getting back to it :) 

as the data were from 2018 thus kinda old, i didn't investigate much the issue... but i guess we can close it now as it's not related to the project, but more about mixpanel
