### ISSUE TITLE
Unable to migrate boards based off of templates

### ISSUE THREAD

**Issue by pmackle** [ak--47/mpMigrate#17]
When trying to migrate a board based off of a template, I get this error - 

`Request failed with status code 400 : extra keys not allowed @ data['template_type']. Got 'E-Commerce'`

Also tried migrating with a Starter Board as another example and got

`ERROR MAKING DASH! X BOARD
Request failed with status code 400 : extra keys not allowed @ data['template_type']. Got 'Starter Board'`

**Comment by ak--47** [comment]
@pmackle this should be fixed by https://github.com/ak--47/mpMigrate/commit/46a48828c183ac9c6b19a5e8c6f1ce056979f2a5

```npx mp-migrate@latest yourConfig.json```
