### ISSUE TITLE
Cohorts are synced but not "selected" in reports and getting errors

### ISSUE THREAD

**Issue by alon-mixpanel** [ak--47/mpMigrate#2]
When syncing the cohorts are synced but the report is shown as broken 
Removing the cohorts and reselecting them resolves this

<img width="1504" alt="image (2)" src="https://user-images.githubusercontent.com/95707406/184940469-0222e3e2-040b-45b4-8ccd-92d1a0f4a054.png">

**Comment by ak--47** [comment]
can confirm this is a bug. priority one is text cards and media object (and layout), but i'll come back to this.

workaround: if you hit the selector in the UI and reselect the cohort... it works. you can then save over it.

**Comment by ak--47** [comment]
the querybuilder's cohort stuff is a bit of a moving target... i've been able to reproduce this... but inconsistently. closing for now and can resurface if it becomes a wider issue. hopefully the "toggling" fix isn't too disruptive.
