### ISSUE TITLE
Incorrect date range applied when migrating event data

### ISSUE THREAD

**Issue by mentatanalytics** [ak--47/mpMigrate#8]
When choosing the migrate events in addition to dashboards, it only exports events from the day that the script is run, regardless of the date range that is provided as input. Screenshots below. This was tested on Feb 7th, 2023. 

Example 1:

<img width="593" alt="Screen Shot 2023-02-07 at 1 34 12 PM" src="https://user-images.githubusercontent.com/107159137/219822101-12399c38-c806-48e8-8ee4-2c2bef556f52.png">

Example 2:

<img width="584" alt="Screen Shot 2023-02-07 at 1 32 01 PM" src="https://user-images.githubusercontent.com/107159137/219822103-36384360-cace-45c4-a1bd-2d8c478f6d24.png">

**Comment by ak--47** [comment]
can reproduce. bug fix incoming.

**Comment by ak--47** [comment]
@mentatanalytics 

this is fixed in v`1.2.0`

https://github.com/ak--47/mpMigrate/pull/11

thank you for reporting!
