### ISSUE TITLE
Bearer token auth clarification

### ISSUE THREAD

**Issue by mentatanalytics** [ak--47/mpMigrate#9]
Not really a bug, just a UX issue. 

It's unclear what value the "Bearer token" refers to. There's no Mixpanel documentation under that name, and [the link included](https://mixpanel.com/oauth/access_token) in the Readme file leads to a blank page that shows a key-value pair, with this format: {'token': [alphanumeric_string]}. If that's the bearer token, it would be helpful to have some clarification as to how that value is retrieved. I tried both the project token and the API secret, both gave authentication errors. 

It would also help to clarify if there's a difference in performance between the bearer token approach and the service account approach.

**Comment by ak--47** [comment]
👍 acknowledged. thanks for pointing this out.

`bearer token` docs will be added in the next release

**Comment by ak--47** [comment]
@mentatanalytics 

this is shipped:
https://github.com/ak--47/mpMigrate/commit/dc808b25ad8c7ed6e2756e29af3ad27951f59a40#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

human readable:
https://github.com/ak--47/mpMigrate#authentication
